# -*- coding: utf-8 -*-
"""01fe21bec223_a1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tNVFUSGQfgDfe4oHVAc4A8R6x9a1BfPe

Q8)
"""

n=int(input("Enter number of rows"))
for i in range(n):
    # nested loop
    for j in range(i):
        # display number
        print('*', end=' ')
    # new line after each row
    print('')

"""Q7

"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
n=int(input("Enter number of elements to be entered into the list"))
a=[]
even=[]
odd=[]
for i in range(n):
  b=int(input("enter the number"))
  a.append(b)
  if(b%2==0):
   even.append(b)
  else:
    odd.append(b)
print(a)

print("Even numbers list = ",even)
print("Odd numbers list =",odd)

"""Q6)string is palindrome or not

"""

string=input("Enter the string")
c=0
l=int(len(string))
n=l
a=list(string)
print(type(a))
b=a
d=1
for i in a:
  if(a[d-1]==b[l-d]):
    c=c+1
    d=d+1
  else:
    break
if(c==l):
  print("string is palindrome")
else:
  print("String is not palindrome")

"""Q5)"""

num = int(input("Enter a number: "))

flag = False

if num == 1:
    print(num, "is not a prime number")
elif num > 1:
    for i in range(2, num):
        if (num % i) == 0:
            flag = True
            break


    if flag:
        print(num, "is not a prime number")
    else:
        print(num, "is a prime number")